---
- name: "Update and upgrade apt packages"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: "Installing deps"
  become: yes
  apt:
    pkg:
      - automake
      - bison
      - flex
      - build-essential
      - git
      - python3
      - python3-dev
      - python3-setuptools
      - libtool
      - libtool-bin
      - libglib2.0-dev
      - wget
      - jupp
      - libpixman-1-dev
      - gcc-8
      - g++-8
      - gcc-8-plugin-dev
      - libc++-8-dev
      - gdb
      - lcov
- name: "Cloning AFLplusplus v2.68c repository"
  git:
    repo: "https://github.com/AFLplusplus/AFLplusplus.git"
    dest: "/home/pi/AFLplusplus"
    clone: yes
    recursive: yes
    force: yes
    accept_hostkey: yes
    version: 2.68c
- stat: path=/home/pi/AFLplusplus/afl-fuzz
  register: afl_fuzz_var
- name: "Make main AFL++ binaries"
  command: "make all"
  when: not afl_fuzz_var.stat.exists
  args:
    chdir: /home/pi/AFLplusplus
- stat: path=/home/pi/AFLplusplus/afl-qemu-trace
  register: afl_qemu_var
- name: "Make QEMU and co"
  command: "make binary-only"
  when: not afl_qemu_var.stat.exists
  environment:
    CPU_TARGET: "aarch64"
  args:
    chdir: /home/pi/AFLplusplus
- stat: path=/usr/local/bin/afl-qemu-trace
  register: afl_global_var
- name: "Install globally"
  command: "make install"
  when: not afl_global_var.stat.exists
  become: yes
  become_user: root
  become_method: sudo
  args:
    chdir: /home/pi/AFLplusplus
